export const countryCodes = [
    {name: "Afghanistan", code: "af"}, 
    {name: "Argentina", code: "ar"}, 
    {name: "Australia", code: "au"}, 
    {name: "Austria", code: "at"}, 
    {name: "Belgium", code: "be"}, 
    {name: "Brazil", code: "br"}, 
    {name: "Bulgaria", code: "bg"}, 
    {name: "Canada", code: "ca"}, 
    {name: "China", code: "cn"}, 
    {name: "Croatia", code: "hr"}, 
    {name: "Czech Republic", code: "cz"}, 
    {name: "Denmark", code: "dk"}, 
    {name: "Ecuador", code: "ec"}, 
    {name: "Finland", code: "fi"}, 
    {name: "France", code: "fr"}, 
    {name: "Germany", code: "de"}, 
    {name: "Hungary", code: "hu"}, 
    {name: "Iceland", code: "is"}, 
    {name: "India", code: "in"}, 
    {name: "Italy", code: "it"}, 
    {name: "Japan", code: "jp"}, 
    {name: "Latvia", code: "lv"}, 
    {name: "Netherlands", code: "nl"}, 
    {name: "Norway", code: "no"}, 
    {name: "Russian Federation", code: "ru"}, 
    {name: "Spain", code: "es"}, 
    {name: "Sweden", code: "se"}, 
    {name: "Switzerland", code: "ch"}, 
    {name: "Ukraine", code: "ua"}, 
    {name: "United Kingdom", code: "gb"}, 
    {name: "United States", code: "us"}
];